
name: gopro overlay

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Update apt
      run: |
        sudo apt update
    - name: Install dependencies
      run: |
        sudo apt install fonts-roboto ffmpeg
        make venv req
    - name: Test with pytest
      run: |
        make ci
    - name: Upload build artefacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: approval-artifacts
        path: ${{ github.workspace }}/tests/approvals/*.png
        retention-days: 2

